# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
url: "https://gallon-liu.github.io"

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Gallon Liu"
description:	       "i'm a handsome dog! my mom says so."
author:              "Gallon Liu"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
